baseURL = "https://usefullog.com/"
theme = "PaperMod"
title = "Useful Log"
languageCode = "en"
defaultContentLanguage = "en"

# this will be included in the footer after the current year the site is last
# built, followed by the (c) symbol
# you can use markdown inside this field
copyright = "by usefullog.com - all copyright reserved"
# copyright = "Some copyright notice - [my license](https://example.com/license)"

[pagination]
    pagerSize = 5  # number of articles per page in the index

summaryLength = 30  # number of words for article summaries


[params]
    author = "usefullog"  # Your name/handle
    description = "Here are a bunch of logs. Some are useful. Some are useless..."  # this will be added as metadata
    ShowReadingTime = false
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    defaultTheme = "auto"  # or "dark"/"light"
    profileModeEnabled = false  # Nice intro/homepage with your bio/photo
    homeInfoParams = { Title = "Useful Log", Content = "Here are a bunch of logs. Some are useful. Some are useless..." }


    # For social icons (add your X handle)
    socialIcons = [
        { name = "x", url = "https://x.com/usefullog" },
        # Add RSS, GitHub, etc. if you want
    ]

    # Enable search, archives, etc.
    fuseOpts = ""  # Enables Fuse.js search

[params.label]
    text = "usefullog.com"
    icon = "/apple-touch-icon.png"
    iconHeight = 32

[params.assets]
    # It's best to put these icons in the "static" folder of your site
    logo = "/android-chrome-192x192.png" #"/logo.svg"
    favicon = "/favicon-32x32.png"  # 32x32
    faviconIco = "/favicon.ico"  # 32x32
    appletouch = "/apple-touch-icon.png"  # 180x180
    # svgicon = "/logo.svg"
    icon512 = "/android-chrome-512x512.png"  # 512x512 png image

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 30
  


